plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id "com.gorylenko.gradle-git-properties" version "2.4.1"

}

group = 'com.kyj'
version = '0.0.1-SNAPSHOT'
description = 'PairTime Backend Auth'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri("http://192.168.56.1:9090/repository/kyj-lib-core/")
        allowInsecureProtocol = true
        credentials {
            username = "admin"
            password = "1234"
        }
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

dependencies {
    // 도메인 모듈 의존성 추가

    // 기타 의존성
    implementation 'com.kyj:kyj-lib-core:0.0.1-SNAPSHOT'
    implementation 'com.kyj:kyj-lib-core-security-auth:0.0.1-SNAPSHOT'
    implementation 'com.kyj:kyj-lib-core-security-client:0.0.1-SNAPSHOT'

    implementation 'com.kyj:pair-time-backend-domain:0.0.1-SNAPSHOT'
    implementation 'com.kyj:kyj-lib-core-rdb:0.0.1-SNAPSHOT'
    implementation 'com.kyj:kyj-lib-core-redis:0.0.1-SNAPSHOT'

    implementation 'org.springframework.boot:spring-boot-starter-actuator' //actuator 추가
    implementation 'io.micrometer:micrometer-registry-prometheus' //프로메테우스가 인식하는 포멧

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    implementation 'io.jsonwebtoken:jjwt-impl:0.12.3'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.5.7'

    //Map struct
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    // Lombok
    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"
    annotationProcessor 'org.projectlombok:lombok'
    compileOnly 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}