plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.kyj'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri("http://192.168.56.1:9090/repository/kyj-lib-core/")
        allowInsecureProtocol = true // HTTP 사용 시 필수
        credentials {
            username = "admin"
            password = "1234"
        }
    }
}
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
dependencies {
    // 개발 편의를 위한 다른 모듈 참조 (빌드에는 포함되지 않음)
//    compileOnly project(':pair-time-backend')
//    compileOnly project(':pair-time-backend-auth')

    // Lombok (먼저 선언)
    compileOnly 'org.projectlombok:lombok'
    compileOnly 'com.kyj:kyj-lib-core:0.0.1-SNAPSHOT'
    annotationProcessor 'org.projectlombok:lombok'

    // JPA 및 관련 의존성 (api로 노출)
    api 'com.kyj:kyj-lib-core-jpa:0.0.1-SNAPSHOT'
    api 'com.querydsl:querydsl-jpa:5.0.0:jakarta'

    // QueryDSL
    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    // Validation
    api 'org.springframework.boot:spring-boot-starter-validation'
}

// 실행 가능한 jar가 아닌 라이브러리로 빌드
bootJar {
    enabled = false
}

jar {
    enabled = true
}

tasks.named('test') {
    useJUnitPlatform()
}
